name: Build
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt-get install meson pkg-config libargtable2-dev libusb-1.0-0-dev git
      - name: Fix subprojects
        run: |
         git clone https://github.com/fifteenhex/libdgpc.git
        working-directory: subprojects
      - name: Setup
        run: meson setup builddir
      - name: Compile
        run: meson compile
        working-directory: builddir
